name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USER_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - uses: actions/checkout@v4
    - name: Build the Docker image for API project
      run: |
        cd src/
        docker build . --file ./Taxi.WebApi/Dockerfile --tag ${{ secrets.ACR_SERVER }}/taxiwebapi:latest
        docker push ${{ secrets.ACR_SERVER }}/taxiwebapi:latest
    - name: Build the Docker image for gRPC project
      run: |
        cd src/
        docker build . --file ./Taxi.gRPC/Dockerfile --tag ${{ secrets.ACR_SERVER }}/taxigrpc:latest
        docker push ${{ secrets.ACR_SERVER }}/taxigrpc:latest

