name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Taxi.sln
    - name: Build
      run: dotnet build ./src/Taxi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Taxi.sln --configuration Release --no-build --verbosity normal
